import cucumber.api.java.en.When;

/**
 * Package: PACKAGE_NAME
 * Generated by: Hoang.Son.Nguyen
 * Generated at: 07.01.2019 2019
 */
public class MyStepdefs {
    @When("^i enter <hoang son> to search$")
    public void iEnterHoangSonToSearch() {
    }
}
