package java.google

import cucumber.api.PendingException
import cucumber.api.java.`is`.En
import cucumber.api.java.en.Given
import cucumber.api.java.en.Then
import cucumber.api.java.en.When

/**
 * Package: java.google
 * Generated by: Hoang.Son.Nguyen
 * Generated at: 07.01.2019 2019
 */
class GoogleHPTest: cucumber.api.java8.En {
    init {
        Given("^i navigate to google hp$")() -> {
            // Write code here that turns the phrase above into concrete actions
            throw PendingException()
        }

        Then("^i see the google HP$", () -> {
            // Write code here that turns the phrase above into concrete actions

        })
        When("^i enter <hoang son> to search$", () -> {
            // Write code here that turns the phrase above into concrete actions


        })


        Then("^i see the result$", () -> {
            // Write code here that turns the phrase above into concrete actions    throw new PendingException();
        })
    }
}